### ISSUE TITLE
Is folding broken in ST3#

### ISSUE THREAD

**Issue by phantom7** [epitron/Julia-sublime#2]
Why does folding sometimes not work?

![strange folding behavior](https://cloud.githubusercontent.com/assets/4007736/4158680/ebc5b93a-3490-11e4-8878-cc69f3194799.jpg)

Thanks!

**Comment by ViktorQvarfordt** [comment]
This is related to Sublime Text itself, not Julia-sublime. Furthermore, I think this is intended behavior. (And this issue is really old :)
