### ISSUE TITLE
bug in folding for functions with arguments over multiple lines

### ISSUE THREAD

**Issue by gasagna** [epitron/Julia-sublime#4]
As the title says, it seems folding is not properly performed for functions with arguments distributed over multiple lines, see attached picture, showing the function repeated twice for convenience, with the first occurence folded.

<img width="236" alt="screen shot 2016-02-06 at 20 46 44" src="https://cloud.githubusercontent.com/assets/744738/12869313/1e3dfa78-cd13-11e5-9db3-71dc1bc65235.png">

Thanks for the great package.

**Comment by gasagna** [comment]
Bump

**Comment by ViktorQvarfordt** [comment]
This is a core sublime issue. Code folding is based on indent only (not syntax or anything else). This is a long-time [requested feature](https://github.com/SublimeTextIssues/Core/issues/101) in sublime.
