### ISSUE TITLE
Auto-indentation not working

### ISSUE THREAD

**Issue by okvs** [epitron/Julia-sublime#7]
Auto-indentation is broken for me on SublimeText3. It's been broken for a couple of weeks I think:

<img width="167" alt="screen shot 2016-05-16 at 19 24 13" src="https://cloud.githubusercontent.com/assets/7106412/15297743/0367fb5e-1b9c-11e6-90e7-ef9fb44097ff.png">

If I switch to a different language (Matlab, Python) indentation works.

**Comment by epitron** [comment]
Hmmm.. I'm not sure what's going wrong there.

This repo is basically a mirror of the TextMate plugin:
  https://github.com/JuliaLang/Julia.tmbundle

They might be able to help you out.

**Comment by epitron** [comment]
Alternately, have you seen Juno (the Atom-based Julia editor)? It looks pretty nice: http://junolab.org/

**Comment by okvs** [comment]
I will try to see if they can help.

As for Juno, I am familiar with it, and use it occasionally. Unfortunately, I have some _serious_ problems with typing lag (probably due to code completion). I find Sublime with the sendtext+ plugin more convenient for simple interaction with the Julia REPL.

**Comment by epitron** [comment]
Ah, yeah, that's why I use sublime as well -- I can't stand latency.

Anyhow, thanks for taking the time to get this resolved. Keep me posted!

**Comment by lewisl** [comment]
Me, too.

It seems to have broken with one of the recent dev builds.  They've been doing a lot of API changes.  On the Sublime Text forum someone responded to my question that this language plug-in contains no indentation rules.  The latest version of the Textmate plugin for Julia does have indentation rules.
